Package: A
Dependencies: B, C

Package: B
Dependencies: C, D

Package: C
Dependencies: E

Package: D
Dependencies: A, F

Package: E
Dependencies: 

Package: F
Dependencies: G

Package: G
Dependencies:
